runtime: python39
entrypoint: gunicorn -b :$PORT app_tocloud:app

env_variables:
  DATABASE_URL: ${DATABASE_URL}
  GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
  SECRET_KEY: ${SECRET_KEY}
  GOOGLE_API_KEY: ${GOOGLE_API_KEY}
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_NAME: ${DB_NAME}
  CLOUD_SQL_CONNECTION_NAME: ${CLOUD_SQL_CONNECTION_NAME}

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

vpc_access_connector:
  name: projects/anespr1-asia-east/locations/asia-east1/connectors/anespr1-connector

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
