runtime: python39
entrypoint: gunicorn -b :$PORT app_tocloud:app

env_variables:
  DATABASE_URL: "mysql+pymysql://root:anespr123@/patients?unix_socket=/cloudsql/anespr1-asia-east:asia-east1:anespr1"
  GOOGLE_CLOUD_PROJECT: "anespr1-asia-east"
  SECRET_KEY: "782a1e73cc19b56e0cfe1ac536f4efff543c7be8b70c6ad18d7fcff9dcacd57b"
  GOOGLE_API_KEY: "AIzaSyCWfpd5kIDmmrKP66gAvDV7uoE-nX2p-w8"
  DB_USER: "root"
  DB_PASS: "anespr123"
  DB_NAME: "patients"
  CLOUD_SQL_CONNECTION_NAME: "anespr1-asia-east:asia-east1:anespr1"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

vpc_access_connector:
  name: projects/anespr1-asia-east/locations/asia-east1/connectors/anespr1-connector

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
